# Generated by Django 2.1.3 on 2018-12-01 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20181201_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 12, 1, 23, 51, 33, 117323)),
        ),
    ]
