# Generated by Django 2.1.3 on 2018-12-08 18:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_auto_20181208_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 12, 8, 23, 34, 50, 361355)),
        ),
    ]
