# Generated by Django 2.1.3 on 2018-12-08 18:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_auto_20181208_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 12, 8, 23, 38, 12, 577577)),
        ),
    ]
